# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://solroshus.com'
baseurl: ''
title: 'Solroshus'
description: 'Valkommen till Solroshuset!'
permalink: pretty
logo: "https://raw.githubusercontent.com/gcrow/solsken/master/img/sunfl_trans.png"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: Blog
  url: /blog/
- title: Details
  url: /details/
- title: Pictures
  url: /pics/
- title: Our Location
  url: /loco/
- title: Map
  url: /map/
- title: Booking
  url: /booking/
- title: About
  url: /about/

# Footer nav
navigation_footer:
- title: Top
  url: "#top"
- title: Home
  url: /
- title: Property Details
  url: /details/
- title: Location
  url: /loco/
- title: Booking
  url: /booking/
- title: Contact
  url: /contact/


# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "The life of Solroshus"
    feature_image: "https://picsum.photos/2560/600?image=866"
